vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    image:
      uri_prefix: /uploads/images
      upload_destination: '%kernel.project_dir%/public/uploads/images'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    video:
      uri_prefix: /uploads/videos
      upload_destination: '%kernel.project_dir%/public/uploads/videos'
      namer:
        service: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true